name: dp-comet
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.12
  - pip
  - pip:
      - numpy
      - pandas
      - matplotlib
      - seaborn
      - tqdm
      - ir-measures
      - ir-datasets
      - pingouin
      - nltk
      - gensim
      - faiss_cpu
      - diffprivlib
      - importlib_resources
      - spacy
      - wn
      - torch
      - transformers